#ifndef ARDOP_APP_SCRIPT_H_
#define ARDOP_APP_SCRIPT_H_

#include <stdbool.h>
#include <stdint.h>

#include "app/spine.h"

/**
 * @file script.h
 * @brief A line-oriented driver for the spine, for use without a user interface.
 *
 * [analysis/14](../analysis/14-station-application.md)'s exit criteria ask for
 * the spine to be driven headless by a scripted command queue. This is that
 * queue, read from a file.
 *
 * The language is the frozen TNC command set plus a handful of directives, and
 * the split is deliberate: `ardop_host_command` is already the tested parser for
 * everything an operator would type, so a second command vocabulary would be a
 * second thing to keep correct. Anything beginning with `@` is a directive here;
 * everything else is a TNC line, passed through unaltered.
 *
 *     # comments and blank lines are ignored
 *     MYCALL N0AAA
 *     ARQBW 2000MAX
 *     ARQCALL N0BBB 2000
 *
 *     @peer LISTEN TRUE     send a TNC line to the other station (loopback only)
 *     @send N               offer N generated bytes, honouring transmit credit
 *     @sendfile PATH        the same, from a file
 *     @wait host=TEXT [Ns]  until a notification containing TEXT arrives
 *     @wait rx=N [Ns]       until the peer has received N bytes
 *     @wait secs=N          advance N seconds of modem time
 *     @expect rx            assert the peer received exactly what @send sent
 *     @expect no-loss       assert no event was lost on either side
 *     @stress display Ns    stop draining the display queue for N seconds
 *     @stats                print queue depths, credit and ownership
 *     @echo TEXT
 *
 * Every timeout is measured in *modem* time -- elapsed samples at 12 kHz -- not
 * wall time. Over the in-memory loopback the two are unrelated, since nothing
 * waits for a device, and a script that passed on a fast machine and timed out
 * on a slow one would be worthless.
 */

typedef struct app_script app_script;

/**
 * @brief Read and parse a script.
 *
 * @param path Script file, or "-" for standard input.
 * @param a    The station the script drives.
 * @param b    The peer for `@peer`, `@wait rx=` and `@expect rx`, or NULL when
 *             there is no second station.
 * @return The script, or NULL (diagnosed on stderr).
 */
app_script *app_script_open(const char *path, app_spine *a, app_spine *b);

/** @brief Free. Safe on NULL. */
void app_script_close(app_script *sc);

/**
 * @brief Run every directive that is ready.
 *
 * Call once per modem step. Directives that wait for something leave the program
 * counter where it is and return, so the caller keeps stepping.
 *
 * @return false when the script has finished or failed.
 */
bool app_script_pump(app_script *sc);

/** @brief Whether the script failed. Meaningful once ::app_script_pump is false. */
bool app_script_failed(const app_script *sc);

/** @brief Offer one drained event. @p side is 0 for @p a and 1 for @p b. */
void app_script_event(app_script *sc, int side, const app_event *ev);

/** @brief Advance the script's clock. @p elapsed is a total, not a delta. */
void app_script_tick(app_script *sc, uint64_t elapsed);

/**
 * @brief Whether the caller should drain the display queue this step.
 *
 * False while `@stress display` is running, which is how that directive
 * manufactures the backpressure it then asserts on.
 */
bool app_script_draining_display(const app_script *sc);

#endif /* ARDOP_APP_SCRIPT_H_ */
